# Generated by Django 4.1.1 on 2022-09-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
    ]
